### PR TITLE
fix: removed extra region from stack defintion file

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

Addresses [Issue-10400](https://github.ibm.com/GoldenEye/issues/issues/10400)

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by imprateeksh** [comment]
`golangci-lint` is [failing](https://github.com/terraform-ibm-modules/dev-rag/actions/runs/10467062970/job/28985110137#step:6:47) in pipeline but passed in local - 

image

**Comment by imprateeksh** [comment]
Getting error in [pipeline](https://github.com/terraform-ibm-modules/dev-rag/actions/runs/10484228042/job/29038261795#step:7:542) Not sure why is this happening. Should we add a sleep here?

image

**Comment by ocofaigh** [comment]
@imprateeksh There are no code changes in this PR. It seems the change your trying to make was already done in https://github.com/terraform-ibm-modules/dev-rag/pull/26

**Pull request closed without merging**
