### PR TITLE
feat: added new standard variation for stack

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Added new variation "standard" for stack, including a compute option of ROKS (instead of CodeEngine) and a platinum version of Elasticsearch.

Also updated version of Elasticsearch DA in both basic and standard.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by toddgiguere** [comment]
Both "basic" and "standard" tests have passed, but the ExistingResources tests seems to be stuck in the undeploy stages:
```
=== NAME  TestProjectsBasicExistingResourcesTest
    tests.go:641: [PROJECTS] Configuration Essential Security - Observability Event Notifications is still undeploying
```
This just repeats.

**Comment by ocofaigh** [comment]
@toddgiguere that usually means its a projects config sync issue. The undeploy might of actually completed in schematics, but the project config is out of sync. Running the `ibmcloud project config-sync` is the current workaround from projects team. If the config and workspace still exist, you could confirm that

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
